// To use add your information below
// type npm run start in the console

// replace the example
const yourInput = {
  message: "Sale order fetched.",
  entity: {
    total_price: 3425.16,
    discount_type: 1,
    discount: 2.0,
    tax: 3.0,
    tax_type: 2,
    total_discount: 69.84,
    tax_amount: 3.0,
    delivery_charges: 0.0,
    coupon: {
      id: null,
      no: null,
      discount_type: null,
      discount: null,
      status: null,
      expiry_date: null,
    },
    shipping_type: 1,
    sale_order_details: [
      {
        id: 4,
        is_misc: null,
        sale_order_id: 3,
        product: {
          id: 2,
          name: "Waterproof IP67 + PD30W Jump Starter",
          weight: 0.0,
          weight_unit: 2,
          sku: "1G020000000001",
          upc: "1G020000000001",
          mlc: "",
          bin: "",
          gtn: "",
          main_category: {
            id: 2,
            name: "Automobile Electronics",
            image:
              "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/330b04dc-aceb-411d-bc11-e79966f491b3",
            slug: "automobile-electronics",
            code: null,
            is_msa_compliant: false,
            parent_id: null,
          },
          created_at: "2023-06-01T09:21:49.618753",
          updated_at: "2023-07-13T10:41:13.463457",
          is_online: true,
          status: 1,
          description: "",
          slug: "1-16-r-c-race-car-with-light",
          is_tobacco: false,
          images: [
            "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/4980ac01-5239-46a5-af19-0ba692ca8770",
          ],
          categories: [
            {
              id: 2,
              name: "Automobile Electronics",
              image:
                "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/330b04dc-aceb-411d-bc11-e79966f491b3",
              slug: "automobile-electronics",
              code: null,
              is_msa_compliant: false,
              parent_id: null,
            },
          ],
          sub_products: [],
        },
        qty: 3,
        unit: 1,
        return_to_stock: null,
        lowest_unit_definition: 1,
        unit_price: 20.0,
        discount_type: 1,
        discount: 0.0,
        picked_qty: 0,
        packed_qty: 0,
      },
      {
        id: 5,
        is_misc: null,
        sale_order_id: 3,
        product: {
          id: 6,
          name: "Kooksoondang Peach Makgeolli",
          weight: 0.0,
          weight_unit: 2,
          sku: "KD010000000001",
          upc: "KD010000000001",
          mlc: "",
          bin: "",
          gtn: "",
          main_category: {
            id: 1,
            name: "testname",
            image: "https://picsum.photos/200/300",
            slug: "testname",
            code: "5678",
            is_msa_compliant: false,
            parent_id: 1,
          },
          created_at: "2023-06-01T09:34:52.574343",
          updated_at: "2023-07-13T10:41:13.463457",
          is_online: true,
          status: 1,
          description: "",
          slug: "kooksoondang-peach-makgeolli",
          is_tobacco: false,
          images: [
            "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/60209af0-a956-4a47-af69-ac4ce9965b64",
          ],
          categories: [
            {
              id: 1,
              name: "testname",
              image: "https://picsum.photos/200/300",
              slug: "testname",
              code: "5678",
              is_msa_compliant: false,
              parent_id: 1,
            },
          ],
          sub_products: [],
        },
        qty: 3,
        unit: 1,
        return_to_stock: null,
        lowest_unit_definition: 1,
        unit_price: 24.0,
        discount_type: 1,
        discount: 0.0,
        picked_qty: 0,
        packed_qty: 0,
      },
      {
        id: 6,
        is_misc: null,
        sale_order_id: 3,
        product: {
          id: 3,
          name: "TWS Earphone AEP-0217",
          weight: 0.0,
          weight_unit: 2,
          sku: "1G020000000002",
          upc: "1G020000000002",
          mlc: "",
          bin: "",
          gtn: "",
          main_category: {
            id: 2,
            name: "Automobile Electronics",
            image:
              "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/330b04dc-aceb-411d-bc11-e79966f491b3",
            slug: "automobile-electronics",
            code: null,
            is_msa_compliant: false,
            parent_id: null,
          },
          created_at: "2023-06-01T09:24:38.177425",
          updated_at: "2023-07-13T10:41:13.463457",
          is_online: true,
          status: 1,
          description: "",
          slug: "1-36-die-cast-pull-back-action-car",
          is_tobacco: false,
          images: [
            "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/da9b396d-8046-4e7f-a939-c51197028f95",
            "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/b18cce92-4098-402d-9ebd-311f0698dfba",
            "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/96273aa5-6d9f-41da-95d2-73a9045f2a3d",
            "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/c9a6c057-4679-4edf-99cf-3f2d26022791",
            "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/2c963a15-50ee-4724-9cc8-090f24f734d9",
          ],
          categories: [
            {
              id: 2,
              name: "Automobile Electronics",
              image:
                "https://khub-app.s3-accelerate.amazonaws.com/media/product/images/330b04dc-aceb-411d-bc11-e79966f491b3",
              slug: "automobile-electronics",
              code: null,
              is_msa_compliant: false,
              parent_id: null,
            },
          ],
          sub_products: [],
        },
        qty: 4,
        unit: 3,
        return_to_stock: null,
        lowest_unit_definition: 42,
        unit_price: 840.0,
        discount_type: 1,
        discount: 0.0,
        picked_qty: 0,
        packed_qty: 0,
      },
    ],
    id: 3,
    no: "SO-230601-KxQgZ",
    peculiar_no: "YVhQbbZk2juLMdFftDQdY4",
    status: 50,
    parent: {
      no: null,
      id: null,
    },
    note: null,
    customer: {
      id: null,
      no: null,
      balance_limit: null,
      balance_limit_check: null,
      tobacco_eligibility: null,
      recent_expiry_in: null,
      name: null,
      username: null,
      email: null,
      password: null,
      balance: null,
      stripe_customer_id: null,
      phone_no: null,
      business_no: null,
      business_name: null,
      business_country: null,
      business_zip_code: null,
      business_city: null,
      business_state: null,
      business_phone_no: null,
      date_of_join: null,
      dba_name: null,
      business_tax_no: null,
      tax_exempt_code: null,
      tax_expiry_date: null,
      business_tax_expiry_date: null,
      is_tax_exempted: null,
      address: null,
      customer_shipping_details: {
        name: null,
        company_name: null,
        telephone_num: null,
        address: null,
        city: null,
        state: null,
        country: null,
        zip_code: null,
        tax_jurisdiction: null,
        is_billing_same: null,
        shipping_no: null,
      },
      customer_billing_details: {
        name: null,
        company_name: null,
        telephone_num: null,
        address: null,
        city: null,
        state: null,
        country: null,
        zip_code: null,
      },
      resale_certificate: null,
      resale_certificate_num: null,
      resale_certificate_expiry: null,
      resale_certificate_expiry_in: null,
      business_certificate: null,
      business_certificate_num: null,
      business_certificate_expiry: null,
      business_certificate_expiry_in: null,
      tobacco_license: null,
      tobacco_license_num: null,
      tobacco_license_expiry: null,
      tobacco_license_expiry_in: null,
      beverage_license: null,
      beverage_license_num: null,
      beverage_license_expiry: null,
      beverage_license_expiry_in: null,
      cash_n_carry: null,
      promotion_acceptance: null,
      class_of_trades: null,
      customer_other_licenses: null,
      tenant_users: {
        id: null,
        first_name: null,
        last_name: null,
      },
      status: null,
      allow_ecom: null,
      tier_id: null,
      invoice_aging: null,
      custom_status: null,
      external_details: null,
      is_active: null,
    },
    order_type: 1,
    other_type_value: "",
    created_at: "2023-06-01T09:39:38.950693",
    updated_at: "2023-06-01T09:39:38.950693",
    order_date: "2023-06-30T00:00:00",
    sale_type: 1,
    dispatch_date: "2023-06-01",
    additional_attributes: {},
    channel: {
      id: 1,
      name: "Primary",
      type: 0,
    },
    channel_id: {
      id: null,
      name: null,
      type: null,
    },
    invoice: {
      id: 3,
      sale_order_id: 3,
      status: 3,
      total_discount: 69.84,
      sub_total: 3492.0,
      total_amount: 3425.16,
      remaining_amount: 0.0,
      due_date: "2023-06-01T00:00:00",
      payments: [
        {
          id: 3,
          no: "PAY-230601-PpYkF",
          payment_type: 1,
          payment_date: "2023-06-01T00:00:00",
          check_date: null,
          check_no: null,
          check_acc_title: null,
          category: 1,
          amount: 3425.16,
          is_cleared: true,
          reference_number: null,
          customer_id: null,
          external_details: {},
        },
      ],
    },
    shipping_detail: {
      name: null,
      company_name: null,
      telephone_num: null,
      address: null,
      city: null,
      state: null,
      country: null,
      zip_code: null,
      tax_jurisdiction: null,
      is_billing_same: null,
      shipping_no: null,
    },
    billing_detail: {
      name: null,
      company_name: null,
      telephone_num: null,
      address: null,
      city: null,
      state: null,
      country: null,
      zip_code: null,
    },
    sale_agent: {
      id: 1,
      first_name: "Smokes On ",
      last_name: "Wheels",
    },
    created_by: {
      id: 1,
      first_name: "Smokes On ",
      last_name: "Wheels",
    },
    external_details: {},
  },
  warnings: [],
};

module.exports = yourInput;
