// To use add your array to the variable
// type npm run start in the console
// your json will be returned in the console

// insert array contents to edit
// and field to check for
// replace the example
const yourInput = {
  array: [
    {
      Values: [],
      ConnectorField: "entity.total_price",
      SystemField: "TotalPrice",
      DataType: "Float",
      DisplayName: "Total Price",
      DisplayOrder: 1,
    },
    {
      Values: [],
      ConnectorField: "entity.discount_type",
      SystemField: "DiscountType",
      DataType: "Integer",
      DisplayName: "Discount Type",
      DisplayOrder: 2,
    },
    {
      Values: [],
      ConnectorField: "entity.discount",
      SystemField: "Discount",
      DataType: "Float",
      DisplayName: "Discount",
      DisplayOrder: 3,
    },
    {
      Values: [],
      ConnectorField: "entity.tax",
      SystemField: "Tax",
      DataType: "Float",
      DisplayName: "Tax",
      DisplayOrder: 4,
    },
    {
      Values: [],
      ConnectorField: "entity.tax_type",
      SystemField: "TaxType",
      DataType: "Integer",
      DisplayName: "Tax Type",
      DisplayOrder: 5,
    },
    {
      Values: [],
      ConnectorField: "entity.total_discount",
      SystemField: "TotalDiscount",
      DataType: "Float",
      DisplayName: "Total Discount",
      DisplayOrder: 6,
    },
    {
      Values: [],
      ConnectorField: "entity.tax_amount",
      SystemField: "TaxAmount",
      DataType: "Float",
      DisplayName: "Tax Amount",
      DisplayOrder: 7,
    },
    {
      Values: [],
      ConnectorField: "entity.delivery_charges",
      SystemField: "DeliveryCharges",
      DataType: "Float",
      DisplayName: "Delivery Charges",
      DisplayOrder: 8,
    },
    {
      Values: [],
      ConnectorField: "entity.coupon.id",
      SystemField: "CouponId",
      DisplayName: "Coupon ID",
      DisplayOrder: 9,
    },
    {
      Values: [],
      ConnectorField: "entity.coupon.no",
      SystemField: "CouponNo",
      DisplayName: "Coupon No",
      DisplayOrder: 10,
    },
    {
      Values: [],
      ConnectorField: "entity.coupon.discount_type",
      SystemField: "CouponDiscountType",
      DisplayName: "Coupon Discount Type",
      DisplayOrder: 11,
    },
    {
      Values: [],
      ConnectorField: "entity.coupon.discount",
      SystemField: "CouponDiscount",
      DisplayName: "Coupon Discount",
      DisplayOrder: 12,
    },
    {
      Values: [],
      ConnectorField: "entity.coupon.status",
      SystemField: "CouponStatus",
      DisplayName: "Coupon Status",
      DisplayOrder: 13,
    },
    {
      Values: [],
      ConnectorField: "entity.coupon.expiry_date",
      SystemField: "CouponExpiryDate",
      DisplayName: "Coupon Expiry Date",
      DisplayOrder: 14,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_type",
      SystemField: "ShippingType",
      DataType: "Integer",
      DisplayName: "Shipping Type",
      DisplayOrder: 15,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].id",
      SystemField: "SaleOrderDetailId",
      DataType: "Integer",
      DisplayName: "Sale Order Detail ID",
      DisplayOrder: 16,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].is_misc",
      SystemField: "SaleOrderDetailIsMisc",
      DisplayName: "Sale Order Detail Is Misc",
      DisplayOrder: 17,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].sale_order_id",
      SystemField: "SaleOrderDetailSaleOrderId",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Sale Order ID",
      DisplayOrder: 18,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.id",
      SystemField: "SaleOrderDetailProductId",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Product ID",
      DisplayOrder: 19,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.name",
      SystemField: "SaleOrderDetailProductName",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Name",
      DisplayOrder: 20,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.weight",
      SystemField: "SaleOrderDetailProductWeight",
      DataType: "Float",
      DisplayName: "Sale Order Detail Product Weight",
      DisplayOrder: 21,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.weight_unit",
      SystemField: "SaleOrderDetailProductWeightUnit",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Product Weight Unit",
      DisplayOrder: 22,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.sku",
      SystemField: "SaleOrderDetailProductSku",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product SKU",
      DisplayOrder: 23,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.upc",
      SystemField: "SaleOrderDetailProductUpc",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Upc",
      DisplayOrder: 24,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.mlc",
      SystemField: "SaleOrderDetailProductMlc",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Mlc",
      DisplayOrder: 25,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.bin",
      SystemField: "SaleOrderDetailProductBin",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Bin",
      DisplayOrder: 26,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.gtn",
      SystemField: "SaleOrderDetailProductGtn",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Gtn",
      DisplayOrder: 27,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.main_category.id",
      SystemField: "SaleOrderDetailProductMainCategoryId",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Product Main Category ID",
      DisplayOrder: 28,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.main_category.name",
      SystemField: "SaleOrderDetailProductMainCategoryName",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Main Category Name",
      DisplayOrder: 29,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.main_category.image",
      SystemField: "SaleOrderDetailProductMainCategoryImage",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Main Category Image",
      DisplayOrder: 30,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.main_category.slug",
      SystemField: "SaleOrderDetailProductMainCategorySlug",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Main Category Slug",
      DisplayOrder: 31,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.main_category.code",
      SystemField: "SaleOrderDetailProductMainCategoryCode",
      DisplayName: "Sale Order Detail Product Main Category Code",
      DisplayOrder: 32,
    },
    {
      Values: [],
      ConnectorField:
        "entity.[sale_order_details].product.main_category.is_msa_compliant",
      SystemField: "SaleOrderDetailProductMainCategoryIsMsaCompliant",
      DataType: "Boolean",
      DisplayName: "Sale Order Detail Product Main Category Is Msa Compliant?",
      DisplayOrder: 33,
    },
    {
      Values: [],
      ConnectorField:
        "entity.[sale_order_details].product.main_category.parent_id",
      SystemField: "SaleOrderDetailProductMainCategoryParentId",
      DisplayName: "Sale Order Detail Product Main Category Parent ID",
      DisplayOrder: 34,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.created_at",
      SystemField: "SaleOrderDetailProductCreatedAt",
      DataType: "DateTime",
      DisplayName: "Sale Order Detail Product Created At",
      DisplayOrder: 35,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.updated_at",
      SystemField: "SaleOrderDetailProductUpdatedAt",
      DataType: "DateTime",
      DisplayName: "Sale Order Detail Product Updated At",
      DisplayOrder: 36,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.is_online",
      SystemField: "SaleOrderDetailProductIsOnline",
      DataType: "Boolean",
      DisplayName: "Sale Order Detail Product Is Online?",
      DisplayOrder: 37,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.status",
      SystemField: "SaleOrderDetailProductStatus",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Product Status",
      DisplayOrder: 38,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.description",
      SystemField: "SaleOrderDetailProductDescription",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Description",
      DisplayOrder: 39,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.slug",
      SystemField: "SaleOrderDetailProductSlug",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Slug",
      DisplayOrder: 40,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.is_tobacco",
      SystemField: "SaleOrderDetailProductIsTobacco",
      DataType: "Boolean",
      DisplayName: "Sale Order Detail Product Is Tobacco?",
      DisplayOrder: 41,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.[images]",
      SystemField: "SaleOrderDetailProductImages",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Images",
      DisplayOrder: 42,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.[categories].id",
      SystemField: "SaleOrderDetailProductCategoryId",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Product Category ID",
      DisplayOrder: 43,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.[categories].name",
      SystemField: "SaleOrderDetailProductCategoryName",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Category Name",
      DisplayOrder: 44,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.[categories].image",
      SystemField: "SaleOrderDetailProductCategoryImage",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Category Image",
      DisplayOrder: 45,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.[categories].slug",
      SystemField: "SaleOrderDetailProductCategorySlug",
      DataType: "Text",
      DisplayName: "Sale Order Detail Product Category Slug",
      DisplayOrder: 46,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.[categories].code",
      SystemField: "SaleOrderDetailProductCategoryCode",
      DisplayName: "Sale Order Detail Product Category Code",
      DisplayOrder: 47,
    },
    {
      Values: [],
      ConnectorField:
        "entity.[sale_order_details].product.[categories].is_msa_compliant",
      SystemField: "SaleOrderDetailProductCategoryIsMsaCompliant",
      DataType: "Boolean",
      DisplayName: "Sale Order Detail Product Category Is Msa Compliant?",
      DisplayOrder: 48,
    },
    {
      Values: [],
      ConnectorField:
        "entity.[sale_order_details].product.[categories].parent_id",
      SystemField: "SaleOrderDetailProductCategoryParentId",
      DisplayName: "Sale Order Detail Product Category Parent ID",
      DisplayOrder: 49,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].product.[sub_products]",
      SystemField: "SaleOrderDetailProductSubProducts",
      DisplayName: "Sale Order Detail Product Sub Products",
      DisplayOrder: 50,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].qty",
      SystemField: "SaleOrderDetailQty",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Qty",
      DisplayOrder: 51,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].unit",
      SystemField: "SaleOrderDetailUnit",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Unit",
      DisplayOrder: 52,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].return_to_stock",
      SystemField: "SaleOrderDetailReturnToStock",
      DisplayName: "Sale Order Detail Return To Stock",
      DisplayOrder: 53,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].lowest_unit_definition",
      SystemField: "SaleOrderDetailLowestUnitDefinition",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Lowest Unit Definition",
      DisplayOrder: 54,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].unit_price",
      SystemField: "SaleOrderDetailUnitPrice",
      DataType: "Float",
      DisplayName: "Sale Order Detail Unit Price",
      DisplayOrder: 55,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].discount_type",
      SystemField: "SaleOrderDetailDiscountType",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Discount Type",
      DisplayOrder: 56,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].discount",
      SystemField: "SaleOrderDetailDiscount",
      DataType: "Float",
      DisplayName: "Sale Order Detail Discount",
      DisplayOrder: 57,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].picked_qty",
      SystemField: "SaleOrderDetailPickedQty",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Picked Qty",
      DisplayOrder: 58,
    },
    {
      Values: [],
      ConnectorField: "entity.[sale_order_details].packed_qty",
      SystemField: "SaleOrderDetailPackedQty",
      DataType: "Integer",
      DisplayName: "Sale Order Detail Packed Qty",
      DisplayOrder: 59,
    },
    {
      Values: [],
      ConnectorField: "entity.id",
      SystemField: "Id",
      DataType: "Integer",
      DisplayName: "ID",
      DisplayOrder: 60,
    },
    {
      Values: [],
      ConnectorField: "entity.no",
      SystemField: "No",
      DataType: "Text",
      DisplayName: "No",
      DisplayOrder: 61,
    },
    {
      Values: [],
      ConnectorField: "entity.peculiar_no",
      SystemField: "PeculiarNo",
      DataType: "Text",
      DisplayName: "Peculiar No",
      DisplayOrder: 62,
    },
    {
      Values: [],
      ConnectorField: "entity.status",
      SystemField: "Status",
      DataType: "Integer",
      DisplayName: "Status",
      DisplayOrder: 63,
    },
    {
      Values: [],
      ConnectorField: "entity.parent.no",
      SystemField: "ParentNo",
      DisplayName: "Parent No",
      DisplayOrder: 64,
    },
    {
      Values: [],
      ConnectorField: "entity.parent.id",
      SystemField: "ParentId",
      DisplayName: "Parent ID",
      DisplayOrder: 65,
    },
    {
      Values: [],
      ConnectorField: "entity.note",
      SystemField: "Note",
      DisplayName: "Note",
      DisplayOrder: 66,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.id",
      SystemField: "CustomerId",
      DisplayName: "Customer ID",
      DisplayOrder: 67,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.no",
      SystemField: "CustomerNo",
      DisplayName: "Customer No",
      DisplayOrder: 68,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.balance_limit",
      SystemField: "CustomerBalanceLimit",
      DisplayName: "Customer Balance Limit",
      DisplayOrder: 69,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.balance_limit_check",
      SystemField: "CustomerBalanceLimitCheck",
      DisplayName: "Customer Balance Limit Check",
      DisplayOrder: 70,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tobacco_eligibility",
      SystemField: "CustomerTobaccoEligibility",
      DisplayName: "Customer Tobacco Eligibility",
      DisplayOrder: 71,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.recent_expiry_in",
      SystemField: "CustomerRecentExpiryIn",
      DisplayName: "Customer Recent Expiry In",
      DisplayOrder: 72,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.name",
      SystemField: "CustomerName",
      DisplayName: "Customer Name",
      DisplayOrder: 73,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.username",
      SystemField: "CustomerUsername",
      DisplayName: "Customer Username",
      DisplayOrder: 74,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.email",
      SystemField: "CustomerEmail",
      DisplayName: "Customer Email",
      DisplayOrder: 75,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.password",
      SystemField: "CustomerPassword",
      DisplayName: "Customer Password",
      DisplayOrder: 76,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.balance",
      SystemField: "CustomerBalance",
      DisplayName: "Customer Balance",
      DisplayOrder: 77,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.stripe_customer_id",
      SystemField: "CustomerStripeCustomerId",
      DisplayName: "Customer Stripe Customer ID",
      DisplayOrder: 78,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.phone_no",
      SystemField: "CustomerPhoneNo",
      DisplayName: "Customer Phone No",
      DisplayOrder: 79,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_no",
      SystemField: "CustomerBusinessNo",
      DisplayName: "Customer Business No",
      DisplayOrder: 80,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_name",
      SystemField: "CustomerBusinessName",
      DisplayName: "Customer Business Name",
      DisplayOrder: 81,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_country",
      SystemField: "CustomerBusinessCountry",
      DisplayName: "Customer Business Country",
      DisplayOrder: 82,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_zip_code",
      SystemField: "CustomerBusinessZipCode",
      DisplayName: "Customer Business ZIP Code",
      DisplayOrder: 83,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_city",
      SystemField: "CustomerBusinessCity",
      DisplayName: "Customer Business City",
      DisplayOrder: 84,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_state",
      SystemField: "CustomerBusinessState",
      DisplayName: "Customer Business State",
      DisplayOrder: 85,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_phone_no",
      SystemField: "CustomerBusinessPhoneNo",
      DisplayName: "Customer Business Phone No",
      DisplayOrder: 86,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.date_of_join",
      SystemField: "CustomerDateOfJoin",
      DisplayName: "Customer Date Of Join",
      DisplayOrder: 87,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.dba_name",
      SystemField: "CustomerDbaName",
      DisplayName: "Customer Dba Name",
      DisplayOrder: 88,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_tax_no",
      SystemField: "CustomerBusinessTaxNo",
      DisplayName: "Customer Business Tax No",
      DisplayOrder: 89,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tax_exempt_code",
      SystemField: "CustomerTaxExemptCode",
      DisplayName: "Customer Tax Exempt Code",
      DisplayOrder: 90,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tax_expiry_date",
      SystemField: "CustomerTaxExpiryDate",
      DisplayName: "Customer Tax Expiry Date",
      DisplayOrder: 91,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_tax_expiry_date",
      SystemField: "CustomerBusinessTaxExpiryDate",
      DisplayName: "Customer Business Tax Expiry Date",
      DisplayOrder: 92,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.is_tax_exempted",
      SystemField: "CustomerIsTaxExempted",
      DisplayName: "Customer Is Tax Exempted",
      DisplayOrder: 93,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.address",
      SystemField: "CustomerAddress",
      DisplayName: "Customer Address",
      DisplayOrder: 94,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.name",
      SystemField: "CustomerShippingDetailsName",
      DisplayName: "Customer Shipping Details Name",
      DisplayOrder: 95,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.company_name",
      SystemField: "CustomerShippingDetailsCompanyName",
      DisplayName: "Customer Shipping Details Company Name",
      DisplayOrder: 96,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.telephone_num",
      SystemField: "CustomerShippingDetailsTelephoneNumber",
      DisplayName: "Customer Shipping Details Telephone Number",
      DisplayOrder: 97,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.address",
      SystemField: "CustomerShippingDetailsAddress",
      DisplayName: "Customer Shipping Details Address",
      DisplayOrder: 98,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.city",
      SystemField: "CustomerShippingDetailsCity",
      DisplayName: "Customer Shipping Details City",
      DisplayOrder: 99,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.state",
      SystemField: "CustomerShippingDetailsState",
      DisplayName: "Customer Shipping Details State",
      DisplayOrder: 100,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.country",
      SystemField: "CustomerShippingDetailsCountry",
      DisplayName: "Customer Shipping Details Country",
      DisplayOrder: 101,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.zip_code",
      SystemField: "CustomerShippingDetailsZipCode",
      DisplayName: "Customer Shipping Details ZIP Code",
      DisplayOrder: 102,
    },
    {
      Values: [],
      ConnectorField:
        "entity.customer.customer_shipping_details.tax_jurisdiction",
      SystemField: "CustomerShippingDetailsTaxJurisdiction",
      DisplayName: "Customer Shipping Details Tax Jurisdiction",
      DisplayOrder: 103,
    },
    {
      Values: [],
      ConnectorField:
        "entity.customer.customer_shipping_details.is_billing_same",
      SystemField: "CustomerShippingDetailsIsBillingSame",
      DisplayName: "Customer Shipping Details Is Billing Same",
      DisplayOrder: 104,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_shipping_details.shipping_no",
      SystemField: "CustomerShippingDetailsShippingNo",
      DisplayName: "Customer Shipping Details Shipping No",
      DisplayOrder: 105,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_billing_details.name",
      SystemField: "CustomerBillingDetailsName",
      DisplayName: "Customer Billing Details Name",
      DisplayOrder: 106,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_billing_details.company_name",
      SystemField: "CustomerBillingDetailsCompanyName",
      DisplayName: "Customer Billing Details Company Name",
      DisplayOrder: 107,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_billing_details.telephone_num",
      SystemField: "CustomerBillingDetailsTelephoneNumber",
      DisplayName: "Customer Billing Details Telephone Number",
      DisplayOrder: 108,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_billing_details.address",
      SystemField: "CustomerBillingDetailsAddress",
      DisplayName: "Customer Billing Details Address",
      DisplayOrder: 109,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_billing_details.city",
      SystemField: "CustomerBillingDetailsCity",
      DisplayName: "Customer Billing Details City",
      DisplayOrder: 110,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_billing_details.state",
      SystemField: "CustomerBillingDetailsState",
      DisplayName: "Customer Billing Details State",
      DisplayOrder: 111,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_billing_details.country",
      SystemField: "CustomerBillingDetailsCountry",
      DisplayName: "Customer Billing Details Country",
      DisplayOrder: 112,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_billing_details.zip_code",
      SystemField: "CustomerBillingDetailsZipCode",
      DisplayName: "Customer Billing Details ZIP Code",
      DisplayOrder: 113,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.resale_certificate",
      SystemField: "CustomerResaleCertificate",
      DisplayName: "Customer Resale Certificate",
      DisplayOrder: 114,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.resale_certificate_num",
      SystemField: "CustomerResaleCertificateNumber",
      DisplayName: "Customer Resale Certificate Number",
      DisplayOrder: 115,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.resale_certificate_expiry",
      SystemField: "CustomerResaleCertificateExpiry",
      DisplayName: "Customer Resale Certificate Expiry",
      DisplayOrder: 116,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.resale_certificate_expiry_in",
      SystemField: "CustomerResaleCertificateExpiryIn",
      DisplayName: "Customer Resale Certificate Expiry In",
      DisplayOrder: 117,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_certificate",
      SystemField: "CustomerBusinessCertificate",
      DisplayName: "Customer Business Certificate",
      DisplayOrder: 118,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_certificate_num",
      SystemField: "CustomerBusinessCertificateNumber",
      DisplayName: "Customer Business Certificate Number",
      DisplayOrder: 119,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_certificate_expiry",
      SystemField: "CustomerBusinessCertificateExpiry",
      DisplayName: "Customer Business Certificate Expiry",
      DisplayOrder: 120,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.business_certificate_expiry_in",
      SystemField: "CustomerBusinessCertificateExpiryIn",
      DisplayName: "Customer Business Certificate Expiry In",
      DisplayOrder: 121,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tobacco_license",
      SystemField: "CustomerTobaccoLicense",
      DisplayName: "Customer Tobacco License",
      DisplayOrder: 122,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tobacco_license_num",
      SystemField: "CustomerTobaccoLicenseNumber",
      DisplayName: "Customer Tobacco License Number",
      DisplayOrder: 123,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tobacco_license_expiry",
      SystemField: "CustomerTobaccoLicenseExpiry",
      DisplayName: "Customer Tobacco License Expiry",
      DisplayOrder: 124,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tobacco_license_expiry_in",
      SystemField: "CustomerTobaccoLicenseExpiryIn",
      DisplayName: "Customer Tobacco License Expiry In",
      DisplayOrder: 125,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.beverage_license",
      SystemField: "CustomerBeverageLicense",
      DisplayName: "Customer Beverage License",
      DisplayOrder: 126,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.beverage_license_num",
      SystemField: "CustomerBeverageLicenseNumber",
      DisplayName: "Customer Beverage License Number",
      DisplayOrder: 127,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.beverage_license_expiry",
      SystemField: "CustomerBeverageLicenseExpiry",
      DisplayName: "Customer Beverage License Expiry",
      DisplayOrder: 128,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.beverage_license_expiry_in",
      SystemField: "CustomerBeverageLicenseExpiryIn",
      DisplayName: "Customer Beverage License Expiry In",
      DisplayOrder: 129,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.cash_n_carry",
      SystemField: "CustomerCashNCarry",
      DisplayName: "Customer Cash N Carry",
      DisplayOrder: 130,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.promotion_acceptance",
      SystemField: "CustomerPromotionAcceptance",
      DisplayName: "Customer Promotion Acceptance",
      DisplayOrder: 131,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.class_of_trades",
      SystemField: "CustomerClassOfTrades",
      DisplayName: "Customer Class Of Trades",
      DisplayOrder: 132,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.customer_other_licenses",
      SystemField: "CustomerOtherLicenses",
      DisplayName: "Customer Other Licenses",
      DisplayOrder: 133,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tenant_users.id",
      SystemField: "CustomerTenantUsersId",
      DisplayName: "Customer Tenant Users ID",
      DisplayOrder: 134,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tenant_users.first_name",
      SystemField: "CustomerTenantUsersFirstName",
      DisplayName: "Customer Tenant Users First Name",
      DisplayOrder: 135,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tenant_users.last_name",
      SystemField: "CustomerTenantUsersLastName",
      DisplayName: "Customer Tenant Users Last Name",
      DisplayOrder: 136,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.status",
      SystemField: "CustomerStatus",
      DisplayName: "Customer Status",
      DisplayOrder: 137,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.allow_ecom",
      SystemField: "CustomerAllowEcom",
      DisplayName: "Customer Allow Ecom",
      DisplayOrder: 138,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.tier_id",
      SystemField: "CustomerTierId",
      DisplayName: "Customer Tier ID",
      DisplayOrder: 139,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.invoice_aging",
      SystemField: "CustomerInvoiceAging",
      DisplayName: "Customer Invoice Aging",
      DisplayOrder: 140,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.custom_status",
      SystemField: "CustomerCustomStatus",
      DisplayName: "Customer Custom Status",
      DisplayOrder: 141,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.external_details",
      SystemField: "CustomerExternalDetails",
      DisplayName: "Customer External Details",
      DisplayOrder: 142,
    },
    {
      Values: [],
      ConnectorField: "entity.customer.is_active",
      SystemField: "CustomerIsActive",
      DisplayName: "Customer Is Active",
      DisplayOrder: 143,
    },
    {
      Values: [],
      ConnectorField: "entity.order_type",
      SystemField: "OrderType",
      DataType: "Integer",
      DisplayName: "Order Type",
      DisplayOrder: 144,
    },
    {
      Values: [],
      ConnectorField: "entity.other_type_value",
      SystemField: "OtherTypeValue",
      DataType: "Text",
      DisplayName: "Other Type Value",
      DisplayOrder: 145,
    },
    {
      Values: [],
      ConnectorField: "entity.created_at",
      SystemField: "CreatedAt",
      DataType: "DateTime",
      DisplayName: "Created At",
      DisplayOrder: 146,
    },
    {
      Values: [],
      ConnectorField: "entity.updated_at",
      SystemField: "UpdatedAt",
      DataType: "DateTime",
      DisplayName: "Updated At",
      DisplayOrder: 147,
    },
    {
      Values: [],
      ConnectorField: "entity.order_date",
      SystemField: "OrderDate",
      DataType: "DateTime",
      DisplayName: "Order Date",
      DisplayOrder: 148,
    },
    {
      Values: [],
      ConnectorField: "entity.sale_type",
      SystemField: "SaleType",
      DataType: "Integer",
      DisplayName: "Sale Type",
      DisplayOrder: 149,
    },
    {
      Values: [],
      ConnectorField: "entity.dispatch_date",
      SystemField: "DispatchDate",
      DataType: "Text",
      DisplayName: "Dispatch Date",
      DisplayOrder: 150,
    },
    {
      Values: [],
      ConnectorField: "entity.channel.id",
      SystemField: "ChannelId",
      DataType: "Integer",
      DisplayName: "Channel ID",
      DisplayOrder: 151,
    },
    {
      Values: [],
      ConnectorField: "entity.channel.name",
      SystemField: "ChannelName",
      DataType: "Text",
      DisplayName: "Channel Name",
      DisplayOrder: 152,
    },
    {
      Values: [],
      ConnectorField: "entity.channel.type",
      SystemField: "ChannelType",
      DataType: "Integer",
      DisplayName: "Channel Type",
      DisplayOrder: 153,
    },
    {
      Values: [],
      ConnectorField: "entity.channel_id.id",
      SystemField: "ChannelId",
      DisplayName: "Channel ID",
      DisplayOrder: 154,
    },
    {
      Values: [],
      ConnectorField: "entity.channel_id.name",
      SystemField: "ChannelIdName",
      DisplayName: "Channel ID Name",
      DisplayOrder: 155,
    },
    {
      Values: [],
      ConnectorField: "entity.channel_id.type",
      SystemField: "ChannelIdType",
      DisplayName: "Channel ID Type",
      DisplayOrder: 156,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.id",
      SystemField: "InvoiceId",
      DataType: "Integer",
      DisplayName: "Invoice ID",
      DisplayOrder: 157,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.sale_order_id",
      SystemField: "InvoiceSaleOrderId",
      DataType: "Integer",
      DisplayName: "Invoice Sale Order ID",
      DisplayOrder: 158,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.status",
      SystemField: "InvoiceStatus",
      DataType: "Integer",
      DisplayName: "Invoice Status",
      DisplayOrder: 159,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.total_discount",
      SystemField: "InvoiceTotalDiscount",
      DataType: "Float",
      DisplayName: "Invoice Total Discount",
      DisplayOrder: 160,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.sub_total",
      SystemField: "InvoiceSubTotal",
      DataType: "Float",
      DisplayName: "Invoice Sub Total",
      DisplayOrder: 161,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.total_amount",
      SystemField: "InvoiceTotalAmount",
      DataType: "Float",
      DisplayName: "Invoice Total Amount",
      DisplayOrder: 162,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.remaining_amount",
      SystemField: "InvoiceRemainingAmount",
      DataType: "Float",
      DisplayName: "Invoice Remaining Amount",
      DisplayOrder: 163,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.due_date",
      SystemField: "InvoiceDueDate",
      DataType: "DateTime",
      DisplayName: "Invoice Due Date",
      DisplayOrder: 164,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].id",
      SystemField: "InvoicePaymentId",
      DataType: "Integer",
      DisplayName: "Invoice Payment ID",
      DisplayOrder: 165,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].no",
      SystemField: "InvoicePaymentNo",
      DataType: "Text",
      DisplayName: "Invoice Payment No",
      DisplayOrder: 166,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].payment_type",
      SystemField: "InvoicePaymentType",
      DataType: "Integer",
      DisplayName: "Invoice Payment Type",
      DisplayOrder: 167,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].payment_date",
      SystemField: "InvoicePaymentDate",
      DataType: "DateTime",
      DisplayName: "Invoice Payment Date",
      DisplayOrder: 168,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].check_date",
      SystemField: "InvoicePaymentCheckDate",
      DisplayName: "Invoice Payment Check Date",
      DisplayOrder: 169,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].check_no",
      SystemField: "InvoicePaymentCheckNo",
      DisplayName: "Invoice Payment Check No",
      DisplayOrder: 170,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].check_acc_title",
      SystemField: "InvoicePaymentCheckAccTitle",
      DisplayName: "Invoice Payment Check Acc Title",
      DisplayOrder: 171,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].category",
      SystemField: "InvoicePaymentCategory",
      DataType: "Integer",
      DisplayName: "Invoice Payment Category",
      DisplayOrder: 172,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].amount",
      SystemField: "InvoicePaymentAmount",
      DataType: "Float",
      DisplayName: "Invoice Payment Amount",
      DisplayOrder: 173,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].is_cleared",
      SystemField: "InvoicePaymentIsCleared",
      DataType: "Boolean",
      DisplayName: "Invoice Payment Is Cleared?",
      DisplayOrder: 174,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].reference_number",
      SystemField: "InvoicePaymentReferenceNumber",
      DisplayName: "Invoice Payment Reference Number",
      DisplayOrder: 175,
    },
    {
      Values: [],
      ConnectorField: "entity.invoice.[payments].customer_id",
      SystemField: "InvoicePaymentCustomerId",
      DisplayName: "Invoice Payment Customer ID",
      DisplayOrder: 176,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.name",
      SystemField: "ShippingDetailName",
      DisplayName: "Shipping Detail Name",
      DisplayOrder: 177,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.company_name",
      SystemField: "ShippingDetailCompanyName",
      DisplayName: "Shipping Detail Company Name",
      DisplayOrder: 178,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.telephone_num",
      SystemField: "ShippingDetailTelephoneNumber",
      DisplayName: "Shipping Detail Telephone Number",
      DisplayOrder: 179,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.address",
      SystemField: "ShippingDetailAddress",
      DisplayName: "Shipping Detail Address",
      DisplayOrder: 180,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.city",
      SystemField: "ShippingDetailCity",
      DisplayName: "Shipping Detail City",
      DisplayOrder: 181,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.state",
      SystemField: "ShippingDetailState",
      DisplayName: "Shipping Detail State",
      DisplayOrder: 182,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.country",
      SystemField: "ShippingDetailCountry",
      DisplayName: "Shipping Detail Country",
      DisplayOrder: 183,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.zip_code",
      SystemField: "ShippingDetailZipCode",
      DisplayName: "Shipping Detail ZIP Code",
      DisplayOrder: 184,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.tax_jurisdiction",
      SystemField: "ShippingDetailTaxJurisdiction",
      DisplayName: "Shipping Detail Tax Jurisdiction",
      DisplayOrder: 185,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.is_billing_same",
      SystemField: "ShippingDetailIsBillingSame",
      DisplayName: "Shipping Detail Is Billing Same",
      DisplayOrder: 186,
    },
    {
      Values: [],
      ConnectorField: "entity.shipping_detail.shipping_no",
      SystemField: "ShippingDetailShippingNo",
      DisplayName: "Shipping Detail Shipping No",
      DisplayOrder: 187,
    },
    {
      Values: [],
      ConnectorField: "entity.billing_detail.name",
      SystemField: "BillingDetailName",
      DisplayName: "Billing Detail Name",
      DisplayOrder: 188,
    },
    {
      Values: [],
      ConnectorField: "entity.billing_detail.company_name",
      SystemField: "BillingDetailCompanyName",
      DisplayName: "Billing Detail Company Name",
      DisplayOrder: 189,
    },
    {
      Values: [],
      ConnectorField: "entity.billing_detail.telephone_num",
      SystemField: "BillingDetailTelephoneNumber",
      DisplayName: "Billing Detail Telephone Number",
      DisplayOrder: 190,
    },
    {
      Values: [],
      ConnectorField: "entity.billing_detail.address",
      SystemField: "BillingDetailAddress",
      DisplayName: "Billing Detail Address",
      DisplayOrder: 191,
    },
    {
      Values: [],
      ConnectorField: "entity.billing_detail.city",
      SystemField: "BillingDetailCity",
      DisplayName: "Billing Detail City",
      DisplayOrder: 192,
    },
    {
      Values: [],
      ConnectorField: "entity.billing_detail.state",
      SystemField: "BillingDetailState",
      DisplayName: "Billing Detail State",
      DisplayOrder: 193,
    },
    {
      Values: [],
      ConnectorField: "entity.billing_detail.country",
      SystemField: "BillingDetailCountry",
      DisplayName: "Billing Detail Country",
      DisplayOrder: 194,
    },
    {
      Values: [],
      ConnectorField: "entity.billing_detail.zip_code",
      SystemField: "BillingDetailZipCode",
      DisplayName: "Billing Detail ZIP Code",
      DisplayOrder: 195,
    },
    {
      Values: [],
      ConnectorField: "entity.sale_agent.id",
      SystemField: "SaleAgentId",
      DataType: "Integer",
      DisplayName: "Sale Agent ID",
      DisplayOrder: 196,
    },
    {
      Values: [],
      ConnectorField: "entity.sale_agent.first_name",
      SystemField: "SaleAgentFirstName",
      DataType: "Text",
      DisplayName: "Sale Agent First Name",
      DisplayOrder: 197,
    },
    {
      Values: [],
      ConnectorField: "entity.sale_agent.last_name",
      SystemField: "SaleAgentLastName",
      DataType: "Text",
      DisplayName: "Sale Agent Last Name",
      DisplayOrder: 198,
    },
    {
      Values: [],
      ConnectorField: "entity.created_by.id",
      SystemField: "CreatedById",
      DataType: "Integer",
      DisplayName: "Created By ID",
      DisplayOrder: 199,
    },
    {
      Values: [],
      ConnectorField: "entity.created_by.first_name",
      SystemField: "CreatedByFirstName",
      DataType: "Text",
      DisplayName: "Created By First Name",
      DisplayOrder: 200,
    },
    {
      Values: [],
      ConnectorField: "entity.created_by.last_name",
      SystemField: "CreatedByLastName",
      DataType: "Text",
      DisplayName: "Created By Last Name",
      DisplayOrder: 201,
    },
  ],
  fields: ["DataType"],
};

module.exports = yourInput;
